version: '3'
services:
  app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
      - 8080:8080
   restart: always  
   depends_on: 
      - mongodb
   networks:
      - backend

  mongodb:
   image: mongo
   restart: always
   ports: 
       - 27018:27017
   environment:
      MONGO_INITDB_ROOT_USERNAME: prajwal
      MONGO_INITDB_ROOT_PASSWORD: 12345
   networks:
      - backend 

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: prajwal
#       ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
#       ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/goDb  

networks:
  backend :
   driver: bridge
     
